# Generated by Django 5.0.6 on 2024-06-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETC_API', '0003_post_img_url_alter_post_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
