# Generated by Django 5.0.6 on 2024-07-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETC_API', '0005_section_created_at_textcontent_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='textcontent',
            name='content_type',
            field=models.CharField(default='T', max_length=1),
        ),
    ]
