# Generated by Django 5.0.6 on 2024-07-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETC_API', '0007_textcontent_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textcontent',
            name='content_type',
            field=models.CharField(choices=[('T', 'Text'), ('C', 'Code'), ('I', 'Img')], default='T', max_length=1),
        ),
        migrations.AlterField(
            model_name='textcontent',
            name='language',
            field=models.CharField(blank=True, choices=[('javascript', 'JavaScript'), ('python', 'Python')], max_length=255, null=True),
        ),
    ]
